package com.example.aston6

object Constants {
    const val NAME_KEY_DETAILS = "NAME_KEY_DETAILS"
    const val NUMBER_KEY_DETAILS = "NUMBER_KEY_DETAILS"
    const val SAVE_STATE_KEY = "SAVE_STATE_KEY"
    const val SAVE_STATE_INT = "SAVE_STATE_INT"
    const val FIRST_FRAGMENT_RESULT_KEY = "FIRST_FRAGMENT_RESULT_KEY"
    const val FIRST_FRAGMENT_BUNDLE_KEY = "FIRST_FRAGMENT_BUNDLE_KEY"
    const val FIRST_FRAGMENT_BUNDLE_KEY_NUMBER = "FIRST_FRAGMENT_BUNDLE_KEY_NUMBER"
    const val FIRST_FRAGMENT_BUNDLE = "FIRST_FRAGMENT_BUNDLE"
    const val TELEPHONE_NUMBER_RESULT_KEY = "TELEPHONE_NUMBER_RESULT_KEY"
    const val TELEPHONE_NUMBER_BUNDLE_KEY = "TELEPHONE_NUMBER_BUNDLE_KEY"
    const val BASE_URL = "https://loremflickr.com/400/400/person?random="
}